apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  namespace: admission-webhook
  name: mutate-memory
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: mutate-memory.example.com
  clientConfig:
    service:
      name: mutate-memory
      namespace: admission-webhook
      path: "/mutate"
      port: 8000
  rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: Namespaced
  admissionReviewVersions:
    - v1
  sideEffects: None
  namespaceSelector:
    matchLabels:
      mutate-memory: "true"
  failurePolicy: Ignore
  timeoutSeconds: 3
