apiVersion: v1
kind: Service
metadata:
  name: mutate-memory
  namespace: admission-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: my-memory-tls
spec:
  selector:
    app: mutate-memory
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
